annotations:
  artifacthub.io/alternativeName: nexus
  artifacthub.io/changes: |-
    - kind: added
      description: "Add ability to store AWS S3 credentials for blob stores in a secret."
    - kind: changed
      description: "Update the Nexus3 OCI image to v3.81.1."
apiVersion: v2
appVersion: 3.81.1
description: Helm chart for Sonatype Nexus 3 OSS.
home: https://www.sonatype.com/products/sonatype-nexus-repository
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/nexus3/icon.png
keywords:
- artifacts
- dependency
- management
- sonatype
- nexus
- repository
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: nexus3
sources:
- https://github.com/sonatype/nexus-public
- https://github.com/sonatype/docker-nexus3
- https://github.com/stevehipwell/helm-charts/
type: application
version: 5.11.0
